//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectMVC_game.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class project_gameEntities : DbContext
    {
        public project_gameEntities()
            : base("name=project_gameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adres> adres { get; set; }
        public virtual DbSet<gra> gras { get; set; }
        public virtual DbSet<klient> klients { get; set; }
        public virtual DbSet<pracownik> pracowniks { get; set; }
        public virtual DbSet<wypozyczenie> wypozyczenies { get; set; }
    }
}
